version: 2
build:
  env:
    NODE_VERSION: 18

services:
  - type: web
    name: pingdaily-backend
    env: node
    buildCommand: npm install && npm run build:server
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_SUBJECT
        value: mailto:pingdaily@example.com
      - key: CLIENT_URL
        sync: false
